### ISSUE TITLE
Montar Rich Picture de cada parte do sistema

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#14]
## Descrição da Issue
Construir versão modularizada do rich Picture, mostrando como cada parte do app funciona separadamente

### Tasks:
- [x] Separar quais as partes mais importantes do app 
- [x] Escolher o foco de cada parte
- [x] Montar os rich pictures

**Comment by EsioFreitas** [comment]
Separar quais as partes mais importantes do app: 
* Tarefas- @gabrielalbino ;
* Inventário,   - @rogerioo ;
* Lojas, como contribuir no habitica - @lucasdutraf ;
* Grupo - @EsioFreitas ;
* Desafios - @youssef-md ;
