### ISSUE TITLE
Organizar apresentação do seminário

### ISSUE THREAD

**Issue by EsioFreitas** [requisitos-habitica/Habitica#27]
# Issue Template

## Descrição da Issue
Devemos escolher 4 tópicos e as 4 respectivas pessoas para apresentá-los no seminário de segunda 1/5/2019

### Tasks:
- [x] Wiki - @youssef-md 
     - [x] Mostrar a wiki;
     - [x] O porque de criarmos uma gitHub pages;
     - [x] O porque das organização das paginas serem daquela forma;
- [x] Organização do time - @lucasdutraf 
     - [x] Organização das apresentações (porque separamos para casa seminário falar 4 pessoas por vez); (Dispensável)
     - [x] Tecnologias de comunicação e como estamos usando-as (fala da rastreabilidade);
     - [x] Issues e zenHub
- [x] Rich Picture - @Phe0 
     - [x] Processo criativo;
     - [x] Mostrar RP principal
     - [x] Modularização;
     - [x] Gamificação @devsalula 
- [x] Argumentações - @EsioFreitas 
     - [x] Entendimento do problema;
     - [x] Pesquisa 
     - [x] Mapeamento das argumentações;
     - [x] Apresentar argumentação principal

**Comment by rogerioo** [comment]
Slides de apresentação finalizados e disponibilizados no drive do time
