### ISSUE TITLE
Casos de Uso Gamificação

### ISSUE THREAD

**Issue by Phe0** [requisitos-habitica/Habitica#79]
## Descrição da Issue
Descrever cada elipse do diagrama de casos de uso em um caso de uso 

### Tasks:
- [x] Obter Tomo de Missão
- [x] Usar Tomo de Missão
- [x] Aceitar Convite de Missão
- [x] Começar Missão
- [x] Fazer Batalha de Missão
- [x] Fazer Missão de Coleta
- [ ] Dar Dano
- [ ] Coletar Itens
- [ ] Perder Vida 
- [ ] Terminar Missão
- [ ] Receber Recompensas
- [ ] Receber Medalha

**Comment by Phe0** [comment]
# UC01 - Obter Tomo de Missão
## 1 Nome do Caso de Uso
Obter Tomo de Missão
## 2 Breve descrição
Obter um Item do Tipo Tomo de Missão para que possa realizar missões
## 3 Atores
Usuário
Sistema

## 4 Fluxo de eventos
### 4.1 Fluxo básico]
Usuário Passar de nível 
Usuário obtém Tomo de Missão

### 4.2 Fluxos alternativos
#### FA01 - Obter Tomo através da Loja
Usuário acessa a loja 
Usuário procura por Tomos de Missão
Ou Usuário compra Tomo de Missão com Moedas
Ou Usuário compra Tomo de Missão com Gemas
Usuário obtém Tomo de Missão

### 4.3 Fluxos de Exceção
#### FE01 - Obter Tomo de Missão Global
Sistema inicia Evento Global
Usuário obtém Tomo de Missão Global

## 5 Pré-condições
Usuário deve estar Logado no Sistema

## 6 Pós-condições
Usuário apresenta item Tomo de Missão no seu inventário
