### ISSUE TITLE
Adicionar artefatos na wiki do projeto

### ISSUE THREAD

**Issue by lucasdutraf** [requisitos-habitica/Habitica#8]
## Descrição da Issue
É necessário adicionar na wiki que já possui deploy os artefatos já produzidos pelo grupo até este momento.

### Tasks:
- [x] Argumentação - Tema
- [x] Argumentação - Abordagem da primeira entrega
- [x] Argumentação - Resultado final do rich picture do grupo
- [x] Rich Picture - Grupo
- [x] Rich Picture - Individual

**Comment by Phe0** [comment]
**Sobre a Disciplina**
https://docs.google.com/document/d/1txFCXlFIuv-31Ndkq1wKqB9n1yykIDgb9wTqFLV6R8M/edit

**Sobre o Habitica**
https://docs.google.com/document/d/1jmBWR5xDh9AdlSPvEx1VxzUG8z598j6ivwJTFjkpe9A/edit

**RPs**
RP Geral -> https://github.com/requisitos-habitica/Habitica/issues/10
RP Inventário -> https://github.com/requisitos-habitica/Habitica/issues/18
RP Grupo -> https://github.com/requisitos-habitica/Habitica/issues/21
RP Lojas -> https://github.com/requisitos-habitica/Habitica/issues/19
RP Desafios -> https://github.com/requisitos-habitica/Habitica/issues/22
RP Tarefas -> https://github.com/requisitos-habitica/Habitica/issues/23
RP Contribuindo -> doing
RP Gamificação -> https://github.com/requisitos-habitica/Habitica/issues/11
RPs Individuais -> https://github.com/requisitos-habitica/Habitica/issues/3

**Argumentações**
Escolha do tema V1 -> https://github.com/requisitos-habitica/Habitica/issues/5
Escolha do tema V2 -> https://github.com/requisitos-habitica/Habitica/issues/6
Funcionalidades no escopo -> https://github.com/requisitos-habitica/Habitica/issues/17
Funcionalidade fora do escopo -> https://github.com/requisitos-habitica/Habitica/issues/16

**Priorização**
First Things First -> https://github.com/requisitos-habitica/Habitica/issues/52
Moscow -> https://github.com/requisitos-habitica/Habitica/issues/45
QFD -> https://github.com/requisitos-habitica/Habitica/issues/51

**Técnicas**
Brainstorming -> https://github.com/requisitos-habitica/habitica/issues/33
Storytelling -> https://github.com/requisitos-habitica/habitica/issues/38
Questionário -> Pegar dados do Drive
5W2H -> https://github.com/requisitos-habitica/habitica/issues/34
Glossário -> https://github.com/requisitos-habitica/habitica/issues/37
Análise de Protocolo -> https://github.com/requisitos-habitica/habitica/issues/38
Matriz de Relação e Referências -> https://docs.google.com/presentation/d/1s77D4FU10wx_Q71O3HysZZhKlGssIgw7dIHVrivPGJU/edit?usp=sharing
Etnografia -> https://docs.google.com/document/d/1wxXU4AOnlJTJIE9xkW4flzigUmPQcg5mxb8mrIiS1mk/edit

**Comment by lucasdutraf** [comment]
Não podemos esquecer de modularizar na wiki e consultar nas respectivas issues data e autor para fazermos uma tabela de controle de versão.

**Comment by youssef-md** [comment]
A medida em que forem terminando editem o comentário do @Phe0 e linkem suas issues.

**Comment by gabrielalbino** [comment]
MosCow -> #45 
First Things First -> #52

**Comment by youssef-md** [comment]
ALELUIAAAA ACABOU TUDOOOOOOOOOOOO !!!!
