### ISSUE TITLE
Verificação: Casos de Uso

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#87]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [ ] Verificar os artefatos do time em cima da checklist
- [ ] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@EsioFreitas

**Comment by EsioFreitas** [comment]
@rogerioo , não entendi o tópico: Verificar os artefatos do time em cima da checklist

**Comment by EsioFreitas** [comment]
Segue a V1 do Registro de inspeção em descrição de caso de uso para a reunião de acompanhamento:
https://docs.google.com/spreadsheets/d/1wW_JU9yvbmNkCMn5jOdZaAeImHbiqxqfkE61XMXbano/edit#gid=0
