### ISSUE TITLE
Verificação: Cenários

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#88]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [x] Verificar os artefatos do time em cima da checklist
- [x] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@Phe0

**Comment by Phe0** [comment]
Inspeção Cenários V1
molde: https://docs.google.com/spreadsheets/d/1uNF-1GBspRnf_8IA5KDEl0PJbd3spIopH95tKn1tO8Y/edit#gid=644845536
preenchido: https://docs.google.com/spreadsheets/d/1vq5QRB4SZGeNxHAg98F_5wJsjjGWI94l3rIaGCV5GfA/edit#gid=1286193854

**Comment by Phe0** [comment]
Inspeção Cenários V2
checklist: https://docs.google.com/document/d/1ctMYOMxpWV8sHArxzGkXV6I-JPxD0D45JWv1iZrMJuM/edit
molde: https://docs.google.com/spreadsheets/d/1Pkwse63CTHDhoMDYQiwwmDB14bGIrkDvg_gxTFiRC8U/edit#gid=1097154786
preenchido: https://docs.google.com/spreadsheets/d/1tkfVfTHQ12mWy77CwMKkN_ruLkCziUgQVAP_Sc9qyMc/edit?usp=drive_web&ouid=110021674732237022958
