### ISSUE TITLE
Verificação: Especificação Suplementar

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#89]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [x] Verificar os artefatos do time em cima da checklist
- [ ] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@devsalula

**Comment by devsalula** [comment]
[Inspeção da Especificação Suplementar](https://docs.google.com/spreadsheets/d/144x8hiYhgfueXARH_aRv-HZBlCN5VFaFsGt7ILzfXlM/edit#gid=0). Falta montar com os resultados.
