### ISSUE TITLE
Verificação: Istar

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#90]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [ ] Verificar os artefatos do time em cima da checklist
- [ ] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@kaiqueborges

**Comment by kaiquebuilds** [comment]
# Checklist Versão 1

Fiz com base nos [slides da aula sobre o i*](https://aprender.ead.unb.br/pluginfile.php/348668/mod_resource/content/10/Requisitos%20-%20Aula%20020a.pdf), focando mais nas regras de representação do framework

Geral
- [ ] Nomes em português
- [ ] Tem Modelo Estratégico de Dependência
- [ ] Tem Modelo de Raciocínio Estratégico
- [ ] Abstrações são representados com o símbolo correto
- [ ] Todas as dependências do SR estão ligadas a alguma abstração do SD

Metas
- [ ] Metas são binárias
- [ ] Descrição no formato "Sujeito + verbo (voz passiva) + complemento"

Metas-flexíveis
- [ ] Descrição no formato "Meta-flexível (critério de qualidade) [tópico]"
- [ ] Metas-flexíveis são graduáveis

Atores
- [ ] Atores estão na especificidade correta (agente, posição, papel)
- [ ] Rationale com área delimitadora
- [ ] Associações entre atores estão corretas

Tarefas
- [ ] Descrição no formato "Verbo/locução verbal (infinitivo) + complemento"

Recursos
- [ ] Descrição no formato "Substantivo"

Links
- [ ] Toda tarefa tem uma seta "means-end" apontando para uma meta, indicando que é um meio para se atingir a meta.
- [ ] Setas de uma mesma dependência na direção correta.
- [ ] Tarefas que têm decomposições usam seta com traço na ponta, indicando as abstrações necessárias para a realização da tarefa.
- [ ] Toda meta-flexível tem links de contribuição de uma abstração - exceto recursos.
- [ ] Toda meta-flexível tem os links de contruibuição com a gradação da contribuição correta.
