### ISSUE TITLE
Verificação: Léxicos

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#91]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [x] Verificar os artefatos do time em cima da checklist
- [x] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@rogerioo

**Comment by rogerioo** [comment]
V1 do checklist disponível [aqui](https://docs.google.com/document/d/1_Oo8YKjfCxGd3fybPG_GNUAX8KoNpwaD-3H887C3PCc/edit?usp=sharing)!

**Comment by rogerioo** [comment]
V2 do checklist disponível [aqui](https://docs.google.com/document/d/11PesPZr5oSv2XIRk68Z_sR5jx5G1XmhCpkNn-_SBWUg/edit?usp=sharing)!

**Comment by rogerioo** [comment]
Resultados disponíveis nessa [tabela](https://docs.google.com/spreadsheets/d/1_KhKRG2dBgvasx4_WQPUEcmnNP_jRz2pKFwVvb0EiWQ/edit?usp=sharing)!
