### ISSUE TITLE
Verificação: NFR

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#92]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [ ] Verificar os artefatos do time em cima da checklist
- [ ] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@youssef-md
