### ISSUE TITLE
Verificação: Ágil

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#93]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [x] Fazer checklist para o artefato
- [x] Verificar os artefatos do time em cima da checklist
- [x] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@lucasdutraf

**Comment by lucasdutraf** [comment]
v1 da Checklist das Histórias de usuário disponível em: https://docs.google.com/spreadsheets/d/10wtjBWkHUA3UD9DI4G0eNvGcjAvfMmEvu-Nisxq-_Pg/edit?usp=sharing
