### ISSUE TITLE
Verificação: Rich Pictures

### ISSUE THREAD

**Issue by rogerioo** [requisitos-habitica/Habitica#98]
## Descrição da Issue
Montar um checklist para o artefato de acordo com os padrões da linguagem e verificar os artefatos produzidos pela equipe. Buscar fontes de informações confiáveis e além do que foi passado em sala.

### Tasks:
- [ ] Fazer checklist para o artefato
- [ ] Verificar os artefatos do time em cima da checklist
- [ ] Montar tabela com os resultados e gerar gráfico em cima dos resultados

## Assignees
@rogerioo

**Comment by rogerioo** [comment]
V1 do checklist disponível [aqui](https://docs.google.com/document/d/1wtd7yqrF7l48YKmX6nUBSv-GBXYGUvhmpHAH_S7SD3A/edit?usp=sharing)!

**Comment by rogerioo** [comment]
Resultados disponíveis nessa [tabela](https://docs.google.com/spreadsheets/d/1pdrrAP4VV6lMihsuCmVTDSidMSyqZoudzhc5FQx6SyE/edit?usp=sharing)!
